require: rubocop-rspec

AllCops:
  Exclude:
    - bin/*

Rails:
  Enabled: true

Lint/Debugger:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%I': '[]'
    '%r': ()
    '%w': '[]'
    '%W': '[]'
